
# Hola everyone :D.
## This is a jupyter notebook for session six in udacity AI programming with python nano degree
### Here we will explore Numpy package and how awesome it is for us :D


# So first question is, why numpy?


In [1]:
import numpy as np

Ok let's try to do a comparison between python and numpy in a matrix multiplication operation ( something you will do extensively when AI programming ) :D

First let's compare initialization time for python and numpy :D

In [26]:
%%timeit

rows, cols = (1000, 1000)
arr = [[1]*cols]*rows

numrows = len(arr)    
numcols = len(arr[0])

4.68 µs ± 38.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [23]:
print(numrows)
print(numcols)

1000
1000


In [29]:
%%timeit

a = np.ones(shape=(1000, 1000))


178 µs ± 3.74 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [30]:
a = np.ones(shape=(1000, 1000))

In [39]:
def python_matMul(mat1, mat2, result):
    # iterating by row of A
    for i in range(len(mat1)):

        # iterating by column by B
        for j in range(len(mat2[0])):

            # iterating by rows of B
            for k in range(len(mat2)):
                result[i][j] += mat1[i][k] * mat2[k][j]

In [41]:
rows, cols = (1000, 1000)
result = [[1]*cols]*rows

%timeit python_matMul(arr, arr, result)

KeyboardInterrupt: 

In [42]:
%timeit res = np.dot(a,a)

29.2 ms ± 1.87 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Awesome, now we know why numpy, let's now see how can we create arrays with numpy and do some magic with them :D

In [49]:
arr1 = np.ones(shape=(2,3), dtype = np.int64)
arr2 = np.ones(shape=(2,3), dtype = np.float64)
arr3 = np.ones(shape=(2,3), dtype = np.uint64)

print(arr1)
print(arr2)
print(arr3)

[[1 1 1]
 [1 1 1]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]]


In [51]:
arr1[1][1] = 2
print(arr1)

[[1 1 1]
 [1 2 1]]


In [54]:
arr1[1][1] = 1.4   # cuz arr1 is of type int
print(arr1)

[[1 1 1]
 [1 1 1]]


In [56]:
arr3[1][1] = -1
print(arr3)

[[                   1                    1                    1]
 [                   1 18446744073709551615                    1]]


In [57]:
print(arr3.shape)

(2, 3)


In [62]:
arr4 = np.ones(shape=(2,2,2), dtype = np.int64)
print(arr4)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [68]:
print(arr4.ndim)
print(arr3.ndim)
print(arr3.dtype)
print(arr4.dtype)

3
2
uint64
int64


In [72]:
arr5 = np.zeros(shape=(2,3), dtype =np.int64)
print(arr5)

[[0 0 0]
 [0 0 0]]


In [73]:
arr6 = np.ones(shape=(2,3), dtype = np.int64)
print(arr6)

[[1 1 1]
 [1 1 1]]


In [97]:
arrx = np.random.rand(2,3)
print(arrx)

[[0.3586029  0.49506747 0.44341196]
 [0.76103901 0.38232541 0.47896584]]


In [100]:
arrx = np.random.randint(1, high=5, size=(2,3), dtype=int)
print(arrx)

[[2 4 3]
 [2 2 3]]


### Numpy arrays concatenation

In [81]:
arr7 = np.concatenate([arr5, arr6], axis = 0)
print(arr7)

[[0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]]


In [82]:
arr8 = np.concatenate([arr5, arr6], axis = 1)
print(arr8)

[[0 0 0 1 1 1]
 [0 0 0 1 1 1]]


In [83]:
arr9 = np.concatenate([arr5, arr6], axis = None)
print(arr9)

[0 0 0 0 0 0 1 1 1 1 1 1]


### convert type of numpy arrays :D

In [85]:
arr10 = np.ones(shape=(2,3), dtype=np.float32)
arr10[1][1] = 5.5

print(arr10)

[[1.  1.  1. ]
 [1.  5.5 1. ]]


In [88]:
arr10 = arr10.astype(np.int64)
print(arr10)

[[1 1 1]
 [1 5 1]]


### Create similar numpy arrays

In [91]:
arr11 = np.ones((2,3))
print(arr11)

[[1. 1. 1.]
 [1. 1. 1.]]


In [92]:
arr12 = np.zeros_like(arr11)
print(arr12)

[[0. 0. 0.]
 [0. 0. 0.]]


In [93]:
arr13 = np.ones_like(arr11)
print(arr13)

[[1. 1. 1.]
 [1. 1. 1.]]


In [102]:
arr14 = np.random.random((3,3))
print(arr14)

[[0.50217733 0.11553707 0.87135965]
 [0.61713825 0.09447975 0.44277831]
 [0.97316617 0.3564178  0.55959231]]


### Arrays constaints :D

#### take care 

You can't append two numpy arrays with different sizes :/

In [104]:
np.ones([7,8]) + np.ones([2,3])

ValueError: operands could not be broadcast together with shapes (7,8) (2,3) 

arrays must be only one Type, unlike python lists that contain multiple types

In [105]:
lst = [1, 1.5, "Hello"]

In [109]:
arr_x = np.ones([2,3], dtype = np.int64)
print(arr_x)

[[1 1 1]
 [1 1 1]]


In [110]:
arr_x[1][1] = "Hello ?!"

ValueError: invalid literal for int() with base 10: 'Hello ?!'

In [111]:
arr_x[1][1] = 5.4231543
print(arr_x)

[[1 1 1]
 [1 5 1]]


## Shaping

In [113]:
a = np.ones([3,3])
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array "a" has 9 elements ( 3 rows * 3 columns)

you can reshape but (number of rows * number of columns) must be == 9 

In [116]:
a = a.reshape(1,9)
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [117]:
a = a.reshape(2,19)

ValueError: cannot reshape array of size 9 into shape (2,19)

In [118]:
b = np.ones([1923, 1385])

### what if you want to reshape "b" to have 3 rows, but you don't know how many columns to make it work ?

and vice verca

In [120]:
b = b.reshape(3, -1)
print(b.shape)

(3, 887785)


In [121]:
b = b.reshape(-1, 3)
print(b.shape)

(887785, 3)


In [122]:
b = b.reshape(-1, 2)

ValueError: cannot reshape array of size 2663355 into shape (2)

## Transposition

In [124]:
a = np.ones([2,3])
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [125]:
a = a.T
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [129]:
a = np.ones([1,2,3,4])
print(a.shape)

(1, 2, 3, 4)


In [130]:
a = a.T
print(a.shape)

(4, 3, 2, 1)


## Mathematical Operations
### Arithmetic operations are element-wise

In [143]:
a = 3*np.ones([2,3])
print(a)

[[3. 3. 3.]
 [3. 3. 3.]]


In [138]:
b = 2*np.ones([2,3])
print(b)

[[2. 2. 2.]
 [2. 2. 2.]]


In [139]:
print(a*b)

[[6. 6. 6.]
 [6. 6. 6.]]


### Logical operators return a boolean element-wise

In [144]:
print(a)

a[0][0] = 10
print(a)

[[3. 3. 3.]
 [3. 3. 3.]]
[[10.  3.  3.]
 [ 3.  3.  3.]]


In [145]:
a > 5

array([[ True, False, False],
       [False, False, False]])

### In-place operations to modify arrays 

In [146]:
print(a)

[[10.  3.  3.]
 [ 3.  3.  3.]]


In [147]:
a /= 2

In [148]:
print(a)

[[5.  1.5 1.5]
 [1.5 1.5 1.5]]


In [149]:
c = np.ones([2,3], dtype = np.int64)

In [150]:
print(a/c)

[[5.  1.5 1.5]
 [1.5 1.5 1.5]]


### math functions

In [151]:
a = np.sqrt(a)
print(a)

[[2.23606798 1.22474487 1.22474487]
 [1.22474487 1.22474487 1.22474487]]


In [153]:
print(a[0,0])
print(a[:,0])

2.23606797749979
[2.23606798 1.22474487]


In [154]:
print(a[0,:])

[2.23606798 1.22474487 1.22474487]


In [155]:
print(a[0,-1])

1.224744871391589


In [156]:
print(a[-1,0])

1.224744871391589


In [158]:
print(a[0,0:2])

[2.23606798 1.22474487]


## Array summation

In [159]:
print(a.sum())

8.359792334457735


In [160]:
print(a.sum(axis = 0))

[3.46081285 2.44948974 2.44948974]


In [161]:
print(a.sum(axis = 1))

[4.68555772 3.67423461]


## Broadcasting

In [162]:
print(a)

[[2.23606798 1.22474487 1.22474487]
 [1.22474487 1.22474487 1.22474487]]


In [163]:
a += 1

In [164]:
print(a)

[[3.23606798 2.22474487 2.22474487]
 [2.22474487 2.22474487 2.22474487]]


In [165]:
a *= 2

In [166]:
print(a)

[[6.47213595 4.44948974 4.44948974]
 [4.44948974 4.44948974 4.44948974]]
