# Quiz One

### Question #1:
What gets printed?

(a) 1, (b) 2, (c) 3, (d) 4, (e) 5


In [1]:
import numpy as np

ary = np.array([1,2,3,5,8])
            #.  2,3,4,6,9
ary = ary + 1

print (ary[1])

3


# Quiz Two

### Question #2:
What gets printed? 

(a) 7, 
(b) 12, 
(c) 10, 
(d) 21, 
(e) 28

In [2]:
import numpy as np

a = np.array([1,2,3,5,8])
b = np.array([0,3,4,2,1])

c = a + b   # c = [1,5,7,7,9]
c = c*a     # c = [1,10,21,....]

print (c[2])

21


# Quiz Three

### Question #3:
What gets printed? 

(a) 0, (b) 1, (c) 2, (d) 3, (e) 5

In [3]:
import numpy as np

a = np.array([1,2,3,5,8])
print (a.ndim)


1


# Quiz Four:

### Question #4:¶
What gets printed? 

(a) 0, (b) 1, (c) 2, (d) 5, (e) 6

In [4]:
import numpy as np

a = np.array([[1,2,3],[0,1,4]])  # shape = 2 rows, 3 colums
                                 # size = 2*3 = 6
print (a.size)

6


# Quiz Five

### Question #5:
What gets printed? 

(a) 0, (b) 1, (c) 5, (d) 8, (e) An exception is thrown

In [ ]:
import numpy as np

a = np.array([[1,2,3],[0,1,4]])
b = np.zeros((2,3), dtype=np.int16)
c = np.ones((2,3), dtype=np.int16)

d = a + b + c
print (d[1,2] )

# Quiz Six
### Question #6:
What gets printed? 

(a) 4, (b) 5, (c) 13, (d) 15, (e) An exception is thrown

In [ ]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.arange(0,10,2)
c = a + b
print (c[4])

# Quiz Seven
### Question #7:
What gets printed? 

(a) 2, (b) 8, (c) 11, (d) 14, (e) An exception is thrown

In [ ]:
import numpy as np

a = np.array([[0, 1, 0], [1, 0, 1]])
a += 3
b = a + 3
print (a[1,2] + b[1,2])

# Quiz Eight
### Question #8:
What gets printed? 

(a) 3, (b) 12, (c) [3, 12], (d) [3, 5, 7], (e) An exception is thrown

In [ ]:
import numpy as np

a = np.array([[0, 1, 2], [3, 4, 5]])
b = a.sum(axis=1)
print (b)

# Quiz Nine
### Question #9:

Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array
```python
lst = [1,2,4,3]
```

In [ ]:
#TODO: Type your code in this cell to solve quiz 9 :D




# Quiz Ten
### Question #10:
8. Write a NumPy program to create a 2d array with 1 on the border and 0 inside. Go to the editor
Expected Output:
Original array:

```
[[ 1. 1. 1. 1. 1.]

 [1. 1. 1. 1. 1. ]
 
 [1. 1. 1. 1. 1. ]
 
[ 1. 1. 1. 1. 1.]]
```

1 on the border and 0 inside in the array

```
[[ 1. 1. 1. 1. 1.]

 [1. 0. 0. 0. 1.]
 
 [1. 0. 0. 0. 1.]
 
[ 1. 1. 1. 1. 1.]]
```

In [ ]:
# TODO: Type code in this cell to solve quiz 10 :D




# Quiz Eleven
### Question #11:

Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern


Sample Output:
Checkerboard pattern: 
```
[[0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                          
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]]
```

In [ ]:
# Todo: Complete code in this cell to solve question 11

